CSE_s1_s2 = { '101'    : 'Engineering Mathematics I',
              '102'    : 'Engineering Mathematics II',
              '103'    : 'Engineering Physics',
              '103P'   : 'Physics Lab',
              '104'    : 'Engineering Chemistry',
              '104P'   : 'Chemistry Lab',
              '105'    : 'Engineering Mechanics',
              '106'    : 'Basics of Civil and Mechanical Engineering',
              '107'    : 'Basics of Electrical, Electronics and Communication Engineering',
              '108'    : 'Engineering Graphics',
              '109P'   : 'Computer Programming in C',
              '110AP'  : 'Mechanical Workshop',
              '110BP'  : 'Electrical and Civil Workshop',
              'c101'   : 4,              'c102'     : 4,
              'c103'   : 3,              'c103P'    : 1,
              'c104'   : 3,              'c104P'    : 1,
              'c105'   : 4,              'c106'     : 4,
              'c107'   : 4,              'c108'     : 3,
              'c109P'  : 3,              'c110AP'   : 2,
              'c110BP' : 2,              'credits'  : 38,
}

CSE_s3 = { '301'     : 'Engineering Mathematics III',
           '302'     : 'Data Structures',
           '303'     : 'Discrete Computational Structures',
           '304'     : 'Humanities and Communication Skills',
           '305'     : 'Electronic Circuits',
           '306'     : 'Switching Theory and Logic Design',
           '307P'    : 'Electronic Circuits Lab',
           '308P'    : 'Programming Lab',
           'c301'    : 4,           'c302'    : 5,
           'c303'    : 4,           'c304'    : 3,
           'c305'    : 4,           'c306'    : 4,
           'c307P'   : 2,           'c308P'   : 2,
           'credits' : 28,
}

CSE_s4 = { '401'     : 'Engineering Mathematics IV',
           '402'     : 'Environmental Studies',
           '403'     : 'Computer Organization and Design',
           '404'     : 'Programming Paradigms',
           '405'     : 'Systems Programming',
           '406'     : 'Microprocessor Based Design',
           '407P'    : 'Data Structures Lab',
           '408P'    : 'Digital Systems Lab',
           'c401'    : 4,           'c402'    : 3,
           'c403'    : 5,           'c404'    : 4,
           'c405'    : 4,           'c406'    : 4,
           'c407P'   : 2,           'c408P'   : 2,
           'credits' : 28,
}

CSE_s5 = { '501'     : 'Software Architecture and Project Management',
           '502'     : 'Industrial Economics and Principles of Management',
           '503'     : 'Signal Processing',
           '504'     : 'Operating Systems',
           '505'     : 'Digital Data Communications',
           '506'     : 'Theory Of Computation',
           '507P'    : 'Programming Paradigm Lab',
           '508P'    : 'Hardware Lab',
           'c501'    : 4,           'c502'    : 3,
           'c503'    : 4,           'c504'    : 5,
           'c505'    : 4,           'c506'    : 4,
           'c507P'   : 2,           'c508P'   : 2,
           'credits' : 28,
}

CSE_s6 = { '601'     : 'Embedded Systems',
           '602'     : 'Compiler Design',
           '603'     : 'Computer Networks',
           '604'     : 'Database Management Systems',
           '605'     : 'Computer Graphics',
           'L01'     : 'Elective I',
           '607P'    : 'Systems Lab',
           '608P'    : 'Mini Project',
           'c601'    : 4,           'c602'    : 5,
           'c603'    : 4,           'c604'    : 4,
           'c605'    : 3,           'cL01'    : 4,
           'c607P'   : 2,           'c608P'   : 2,
           'credits' : 28,
}

CSE_s7 = { '701'     : 'Wireless Networks and Mobile Communication Systems',
           '702'     : 'Design and Analysis of Algorithms',
           '703'     : 'Internet Technology',
           '704'     : 'Cryptography and Network Security',
           'L02'     : 'Elective II',
           'L03'     : 'Elective III',
           '707P'    : 'Compiler Lab',
           '708P'    : 'Network Programming Lab',
           '709P'    : 'Project',
           'c701'    : 3,           'c702'    : 5,
           'c703'    : 3,           'c704'    : 4,
           'cL02'    : 4,           'cL03'    : 4,
           'c707P'   : 2,           'c708P'   : 2,
           'c709P'   : 1,           'credits' : 28,
}

CSE_s8 = { '801'     : 'Computer Architecture and Parallel Processing',
           '802'     : 'Data Mining and Warehousing',
           'L04'     : 'Elective IV',
           'L05'     : 'Elective V',
           '805P'    : 'Project',
           '806P'    : 'Seminar',
           '807P'    : 'Viva Voce',
           'c801'    : 5,           'c802'    : 3,
           'cL04'    : 4,           'cL05'    : 4,
           'c805P'   : 7,           'c806P'   : 2,
           'c807P'   : 3,           'credits' : 28,
}

CSE = { 's1_s2'   : CSE_s1_s2,
        's3'      : CSE_s3,
        's4'      : CSE_s4,
        's5'      : CSE_s5,
        's6'      : CSE_s6,
        's7'      : CSE_s7,
        's8'      : CSE_s8,
        'credits' : 206
}


ECE_s1_s2 = { '101'      : 'Engineering Mathematics I',
              '102'      : 'Engineering Mathematics II',
              '103'      : 'Engineering Physics',
              '103P'     : 'Physics Lab',
              '104'      : 'Engineering Chemistry',
              '104P'     : 'Chemistry Lab',
              '105'      : 'Engineering Mechanics',
              '106'      : 'Basics of Civil and Mechanical Engineering',
              '107'      : 'Basics of Electrical, Electronics and Communication Engineering',
              '108'      : 'Engineering Graphics',
              '109P'     : 'Computer Programming in C',
              '110AP'    : 'Mechanical Workshop',
              '110BP'    : 'Electrical and Civil Workshop',
              'c101'     : 4,              'c102'     : 4,
              'c103'     : 3,              'c103P'    : 1,
              'c104'     : 3,              'c104P'    : 1,
              'c105'     : 4,              'c106'     : 4,
              'c107'     : 4,              'c108'     : 3,
              'c109P'    : 3,              'c110AP'   : 2,
              'c110BP'   : 2,              'credits'  : 38,
}

ECE_s3 = { '301'     : 'Engineering Mathematics III',
           '302'     : 'Humanities and Communications Skills',
           '303'     : 'Network Analysis & Synthesis',
           '304'     : 'Signals and Systems',
           '305'     : 'Digital Electronics',
           '306'     : 'Electrical Engineering',
           '307P'    : 'Digital Electronics Lab',
           '308P'    : 'Electrical Engineering Lab',
           'c301'    : 4,           'c302'    : 3,
           'c303'    : 5,           'c304'    : 4,
           'c305'    : 4,           'c306'    : 4,
           'c307P'   : 2,           'c308P'   : 2,
           'credits' : 28,
}

ECE_s4 = { '401'     : 'Engineering Mathematics IV',
           '402'     : 'Environmental Science',
           '403'     : 'Electronic Circuits',
           '404'     : 'Analog Communication',
           '405'     : 'Computer Organization & Architecture',
           '406'     : 'Solid State Devices',
           '407P'    : 'Electronic Circuits Lab',
           '408P'    : 'Analog Communication Lab',
           'c401'    : 4,           'c402'    : 3,
           'c403'    : 5,           'c404'    : 4,
           'c405'    : 4,           'c406'    : 4,
           'c407P'   : 2,           'c408P'   : 2,
           'credits' : 28,
}

ECE_s5 = { '501'     : 'Digital Signal Processing',
           '502'     : 'Quantitative Techniques for Managerial Decisions',
           '503'     : 'Electromagnetic Field Theory',
           '504'     : 'Digital Communication',
           '505'     : 'Microprocessors & Microcontrollers',
           '506'     : 'Linear Integrated Circuits',
           '507P'    : 'Microprocessors & Microcontrollers Lab',
           '508P'    : 'Linear Integrated Circuits Lab',
           'c501'    : 5,           'c502'    : 4,
           'c503'    : 4,           'c504'    : 4,
           'c505'    : 4,           'c506'    : 3,
           'c507P'   : 2,           'c508P'   : 2,
           'credits' : 28,
}

ECE_s6 = { '601'     : 'Basics of VLSI Design',
           '602'     : 'Engineering Economics and Principles of Management',
           '603'     : 'Radiation and Propagation',
           '604'     : 'Control Systems',
           '605'     : 'Optical Communication',
           'L01'     : 'Elective I',
           '607P'    : 'Digital Communication & DSP Lab',
           '608P'    : 'Mini Project',
           'c601'    : 5,           'c602'    : 4,
           'c603'    : 4,           'c604'    : 4,
           'c605'    : 3,           'cL01'    : 4,
           'c607P'   : 2,           'c608P'   : 2,
           'credits' : 28,
}

ECE_s7 = { '701'     : 'Information Theory and Coding',
           '702'     : 'Microwave Engineering',
           '703'     : 'Analog & Mixed MOS Circuits',
           '704'     : 'Digital System Design',
           'L02'     : 'Elective II',
           'L03'     : 'Elective III',
           '707P'    : 'Communication Systems Lab',
           '708P'    : 'VLSI Design Lab',
           '709P'    : 'Project',
           'c701'    : 5,           'c702'    : 4,
           'c703'    : 3,           'c704'    : 3,
           'cL02'    : 4,           'cL03'    : 4,
           'c707P'   : 2,           'c708P'   : 2,
           'c709P'   : 1,           'credits' : 28,
}

ECE_s8 = { '801'     : 'Data & Communication Network',
           '802'     : 'Wireless Mobile Communication',
           'L04'     : 'Elective IV',
           'L05'     : 'Elective V',
           '805P'    : 'Seminar',
           '806P'    : 'Project',
           '807P'    : 'Viva Voce',
           'c801'    : 5,           'c802'    : 3,
           'cL04'    : 4,           'cL05'    : 4,
           'c805P'   : 2,           'c806P'   : 7,
           'c807P'   : 3,           'credits' : 28,
}

ECE = { 's1_s2'   : ECE_s1_s2,
        's3'      : ECE_s3,
        's4'      : ECE_s4,
        's5'      : ECE_s5,
        's6'      : ECE_s6,
        's7'      : ECE_s7,
        's8'      : ECE_s8,
        'credits' : 206
}

STREAM = { 'Computer Science and Engineering'          : CSE,
           'Electronics and Communication Engineering' : ECE }

STREAM_CODE = { 'CSE' : 'Computer Science and Engineering',
                'ECE' : 'Electronics and Communication Engineering'}
