from collections import OrderedDict

s1_s2 = { '101'    : 'Engineering Mathematics I',
          '102'    : 'Engineering Mathematics II',
          '103'    : 'Engineering Physics',
          '103P'   : 'Physics Lab',
          '104'    : 'Engineering Chemistry',
          '104P'   : 'Chemistry Lab',
          '105'    : 'Engineering Mechanics',
          '106'    : 'Basics of Civil and Mechanical Engineering',
          '107'    : 'Basics of Electrical, Electronics and Communication Engineering',
          '108'    : 'Engineering Graphics',
          '109P'   : 'Computer Programming in C',
          '110AP'  : 'Mechanical Workshop',
          '110BP'  : 'Electrical and Civil Workshop',
          'c101'   : 4,              'c102'     : 4,
          'c103'   : 3,              'c103P'    : 1,
          'c104'   : 3,              'c104P'    : 1,
          'c105'   : 4,              'c106'     : 4,
          'c107'   : 4,              'c108'     : 3,
          'c109P'  : 3,              'c110AP'   : 2,
          'c110BP' : 2,              'credits'  : 38,
}


AE_s1_s2 = s1_s2

AE_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Social Science',
          '303'     : 'Fluid Mechanics and Hydraulic Machinery',
          '304'     : 'Computer Assisted Machine Drawing',
          '305'     : 'Electrical Technology',
          '306'     : 'Metallurgy and Material Science',
          '307P'    : 'Electrical Engineering Lab',
          '308P'    : 'Production Engineering Lab',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

AE_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Science',
          '403'     : 'Aircraft Structure I',
          '404'     : 'Heat Transfer',
          '405'     : 'Mechanics of Solids',
          '406'     : 'Elements of Aeronautics',
          '407P'    : 'Material Testing Lab',
          '408P'    : 'Aircraft Structure Lab I',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

AE_s5 = { '501'     : 'Microprocessor & Applications',
          '502'     : 'Control Engineering',
          '503'     : 'Numerical Methods',
          '504'     : 'Flight Dynamics',
          '505'     : 'Aircraft Structure II',
          '506'     : 'Aerodynamics I',
          '507P'    : 'Aircraft Structures Lab II',
          '508P'    : 'Aircraft Structures Repairs and Maintenance Lab',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

AE_s6 = { '601'     : 'Propulsion I',
          '602'     : 'Aircraft Systems, Instrumentation and Applications',
          '603'     : 'Experimental Stress Analysis',
          '604'     : 'Aero Dynamics II',
          '605'     : 'Computer Integrated Manufacturing',
          'L01'     : 'Elective I',
          '607P'    : 'Mini Project / Lab',
          '608P'    : 'Aerodynamics Lab',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

AE_s7 = { '701'     : 'Propulsion II',
          '702'     : 'Avionics',
          '703'     : 'Workshop Technology',
          '704'     : 'Computational Fluid Dynamics',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Avionics Lab',
          '708P'    : 'Propulsion Lab ',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

AE_s8 = { '801'     : 'Reliability Engineering',
          '802'     : 'Air Craft Rules and Regulations C.A.R I and II',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

AE = { 's1_s2'    : AE_s1_s2,
        's3'      : AE_s3,
        's4'      : AE_s4,
        's5'      : AE_s5,
        's6'      : AE_s6,
        's7'      : AE_s7,
        's8'      : AE_s8,
        'credits' : 206
}


AEIE_s1_s2 = s1_s2

AEIE_s3 = { '301'     : 'Engineering Mathematics III',
            '302'     : 'Humanities and Communication Skills',
            '303'     : 'Electronic Circuits I',
            '304'     : 'Electrical Engineering',
            '305'     : 'Digital Systems',
            '306'     : 'Electric Circuits and Network Theory',
            '307P'    : 'Electronics Lab',
            '308P'    : 'Electrical Engineering Lab',
            'c301'    : 4,           'c302'    : 3,
            'c303'    : 5,           'c304'    : 4,
            'c305'    : 4,           'c306'    : 4,
            'c307P'   : 2,           'c308P'   : 2,
            'credits' : 28,
}

AEIE_s4 = { '401'     : 'Engineering Mathematics IV',
            '402'     : 'Environmental Science',
            '403'     : 'Linear integrated circuits & Applications',
            '404'     : 'Introduction to Microprocessors',
            '405'     : 'Electronic Circuits  II',
            '406'     : 'Electronic Instrumentation & Measurements',
            '407P'    : 'Analog Electronics Lab',
            '408P'    : 'Digital Electronics Lab',
            'c401'    : 4,           'c402'    : 3,
            'c403'    : 5,           'c404'    : 4,
            'c405'    : 4,           'c406'    : 4,
            'c407P'   : 2,           'c408P'   : 2,
            'credits' : 28,
}

AEIE_s5 = { '501'     : 'Advanced Microprocessors & Microcontrollers',
            '502'     : 'Signals & Systems',
            '503'     : 'Control Engineering',
            '504'     : 'Computer Organization & Architecture',
            '505'     : 'Power Electronics',
            '506'     : 'Transducers',
            '507P'    : 'Power Electronics Lab',
            '508P'    : 'Microprocessor & Microcontroller Lab',
            'c501'    : 5,           'c502'    : 4,
            'c503'    : 4,           'c504'    : 4,
            'c505'    : 4,           'c506'    : 3,
            'c507P'   : 2,           'c508P'   : 2,
            'credits' : 28,
}

AEIE_s6 = { '601'     : 'Digital Signal Processing',
            '602'     : 'Engineering Economics and Principles of Management',
            '603'     : 'Biomedical Instrumentation',
            '604'     : 'Advanced Control Theory',
            '605'     : 'Industrial Instrumentation',
            'L01'     : 'Elective I',
            '607P'    : 'Instrumentation Lab',
            '608P'    : 'Mini Project',
            'c601'    : 5,           'c602'    : 4,
            'c603'    : 4,           'c604'    : 4,
            'c605'    : 3,           'cL01'    : 4,
            'c607P'   : 2,           'c608P'   : 2,
            'credits' : 28,
}

AEIE_s7 = { '701'     : 'Process Control Instrumentation',
            '702'     : 'Advanced Instrumentation',
            '703'     : 'Electronic Communication Systems',
            '704'     : 'Analog and Digital Circuit Design',
            'L02'     : 'Elective II',
            'L03'     : 'Elective III',
            '707P'    : 'System Simulation Lab',
            '708P'    : 'Process Control Instrumentation Lab',
            '709P'    : 'Project',
            'c701'    : 5,           'c702'    : 4,
            'c703'    : 3,           'c704'    : 3,
            'cL02'    : 4,           'cL03'    : 4,
            'c707P'   : 2,           'c708P'   : 2,
            'c709P'   : 1,           'credits' : 28,
}

AEIE_s8 = { '801'     : 'Analytical and Opto-electronic Instrumentation',
            '802'     : 'Data & Computer Communication',
            'L04'     : 'Elective IV',
            'L05'     : 'Elective V',
            '805P'    : 'Seminar',
            '806P'    : 'Project',
            '807P'    : 'Viva Voce',
            'c801'    : 5,           'c802'    : 3,
            'cL04'    : 4,           'cL05'    : 4,
            'c805P'   : 2,           'c806P'   : 7,
            'c807P'   : 3,           'credits' : 28,
}

AEIE = { 's1_s2'   : AEIE_s1_s2,
         's3'      : AEIE_s3,
         's4'      : AEIE_s4,
         's5'      : AEIE_s5,
         's6'      : AEIE_s6,
         's7'      : AEIE_s7,
         's8'      : AEIE_s8,
         'credits' : 206
}


AME_s1_s2 = s1_s2

AME_s3 = { '301'     : 'Engineering Mathematics III',
           '302'     : 'Humanities and Communication Skills',
           '303'     : 'Fluid mechanics',
           '304'     : 'Computer Assisted Machine Drawing',
           '305'     : 'Thermodynamics ',
           '306'     : 'Metallurgy and Material Science',
           '307P'    : 'Fluids lab',
           '308P'    : 'Material testing lab',
           'c301'    : 4,           'c302'    : 3,
           'c303'    : 5,           'c304'    : 4,
           'c305'    : 4,           'c306'    : 4,
           'c307P'   : 2,           'c308P'   : 2,
           'credits' : 28,
}

AME_s4 = { '401'     : 'Engineering Mathematics IV',
           '402'     : 'Environmental Science',
           '403'     : 'Auto chassis',
           '404'     : 'Fluid machinery',
           '405'     : 'Mechanics of Solids',
           '406'     : 'Electrical Technology',
           '407P'    : 'Electrical engineering lab ',
           '408P'    : 'Auto chassis lab',
           'c401'    : 4,           'c402'    : 3,
           'c403'    : 5,           'c404'    : 4,
           'c405'    : 4,           'c406'    : 4,
           'c407P'   : 2,           'c408P'   : 2,
           'credits' : 28,
}

AME_s5 = { '501'     : 'Heat and Mass Transfer',
           '502'     : 'Automotive Transmission',
           '503'     : 'Engineering Economics and Principles of Management',
           '504'     : 'IC Engines and Gas Turbines ',
           '505'     : 'Mechanics of Machinery',
           '506'     : 'Casting and Joining',
           '507P'    : 'Machine Shop',
           '508P'    : 'Vehicle Reconditioning Lab',
           'c501'    : 5,           'c502'    : 4,
           'c503'    : 4,           'c504'    : 4,
           'c505'    : 4,           'c506'    : 3,
           'c507P'   : 2,           'c508P'   : 2,
           'credits' : 28,
}

AME_s6 = { '601'     : 'Vehicle Dynamics',
           '602'     : 'Metrology and Instrumentation',
           '603'     : 'Machine Design I',
           '604'     : 'Metal Cutting and Forming',
           '605'     : 'Computer Integrated Manufacturing',
           'L01'     : 'Elective I',
           '607P'    : 'Thermal Lab I',
           '608P'    : 'Instrumentation Lab',
           'c601'    : 5,           'c602'    : 4,
           'c603'    : 4,           'c604'    : 4,
           'c605'    : 3,           'cL01'    : 4,
           'c607P'   : 2,           'c608P'   : 2,
           'credits' : 28,
}

AME_s7 = { '701'     : 'Machine Design II',
           '702'     : 'Operation Management',
           '703'     : 'Auto Electrical & Electronics',
           '704'     : 'Auto power plant',
           'L02'     : 'Elective II',
           'L03'     : 'Elective III',
           '707P'    : 'CAD Lab',
           '708P'    : 'Thermal Lab II',
           '709P'    : 'Project ',
           'c701'    : 5,           'c702'    : 4,
           'c703'    : 3,           'c704'    : 3,
           'cL02'    : 4,           'cL03'    : 4,
           'c707P'   : 2,           'c708P'   : 2,
           'c709P'   : 1,           'credits' : 28,
}

AME_s8 = { '801'     : 'Transport Refrigeration and Air Conditioning',
           '802'     : 'Vehicle Maintenance and Testing',
           'L04'     : 'Elective IV',
           'L05'     : 'Elective V',
           '805P'    : 'Seminar',
           '806P'    : 'Project',
           '807P'    : 'Viva Voce',
           'c801'    : 5,           'c802'    : 3,
           'cL04'    : 4,           'cL05'    : 4,
           'c805P'   : 2,           'c806P'   : 7,
           'c807P'   : 3,           'credits' : 28,
}

AME = { 's1_s2'   : AME_s1_s2,
        's3'      : AME_s3,
        's4'      : AME_s4,
        's5'      : AME_s5,
        's6'      : AME_s6,
        's7'      : AME_s7,
        's8'      : AME_s8,
        'credits' : 206
}


BT_s1_s2 = s1_s2

BT_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities & Communication Skills',
          '303'     : 'Fluid Flow Operations',
          '304'     : 'Microbiology',
          '305'     : 'Biochemistry I',
          '306'     : 'Bioprocess Calculations',
          '307P'    : 'Microbiology Lab',
          '308P'    : 'Biochemistry Lab',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

BT_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Science',
          '403'     : 'Chemical Reaction Engg',
          '404'     : 'Biochemistry II',
          '405'     : 'Cell Biology',
          '406'     : 'Mechanical Operations',
          '407P'    : 'Fluid Flow and Mechanical perations lab',
          '408P'    : 'Bioanalytical Techniques Lab',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

BT_s5 = { '501'     : 'Mass Transfer Operations',
          '502'     : 'Molecular Biology',
          '503'     : 'Enzyme Science and Engg',
          '504'     : 'Thermodynamics & Heat Transfer Operations',
          '505'     : 'Bioinformatics',
          '506'     : 'Process Instrumentation',
          '507P'    : 'Heat and Mass Transfer Lab',
          '508P'    : 'Bioprocess Engg. Lab ',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

BT_s6 = { '601'     : 'Genetic Engineering',
          '602'     : 'Bioprocess Engineering',
          '603'     : 'Financial Management & Cost Estimation of Process Industries',
          '604'     : 'Process dynamics & control',
          '605'     : 'Food Biotechnology',
          'L01'     : 'Elective I',
          '607P'    : 'Molecular Biology & Genetic Engg. Lab',
          '608P'    : 'Bioinformatics Lab ',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

BT_s7 = { '701'     : 'Bioprocess Plant Design',
          '702'     : 'Downstream Processing',
          '703'     : 'Environmental Engineering',
          '704'     : 'Immunology & Immuno-technology',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Downstream Processing Lab',
          '708P'    : 'Reaction Engg& Process Control Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

BT_s8 = { '801'     : 'Plant Operations, Safety and Biosafety',
          '802'     : 'Industrial Biotechnology and Biopharmaceuticals',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

BT = { 's1_s2'   : BT_s1_s2,
       's3'      : BT_s3,
       's4'      : BT_s4,
       's5'      : BT_s5,
       's6'      : BT_s6,
       's7'      : BT_s7,
       's8'      : BT_s8,
       'credits' : 206
}


BE_s1_s2 = s1_s2

BE_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Communication Skills',
          '303'     : 'Life Science',
          '304'     : 'Electrical Technology',
          '305'     : 'Digital Principles and Design',
          '306'     : 'Analog Electronics',
          '307P'    : 'Basic Electronics Lab',
          '308P'    : 'Electrical Engineering Lab',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

BE_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Science',
          '403'     : 'Signals and Systems',
          '404'     : 'Electronic Instrumentation',
          '405'     : 'Linear Integrated Circuits',
          '406'     : 'Microprocessors and Interfacing',
          '407P'    : 'Electronic Circuits Lab',
          '408P'    : 'Digital Electronics Lab ',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

BE_s5 = { '501'     : 'Digital Signal Processing',
          '502'     : 'Medical Physics',
          '503'     : 'Advanced Microprocessors and Microcontrollers',
          '504'     : 'Computer Organization and Architecture',
          '505'     : 'Biosensors and Transducers',
          '506'     : 'Medical Instrumentation',
          '507P'    : 'Medical Electronics Lab',
          '508P'    : 'Microprocessors and Microcontrollers Lab',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

BE_s6 = { '601'     : 'Bio-signal Processing Techniques and Applications',
          '602'     : 'Engineering Economics and Principles of Management',
          '603'     : 'Medical Imaging Techniques',
          '604'     : 'Control Systems',
          '605'     : 'Biomedical Equipments and Biophotonics',
          'L01'     : 'Elective I',
          '607P'    : 'Biomedical and Clinical Instrumentation Lab',
          '608P'    : 'Mini Project',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

BE_s7 = { '701'     : 'Digital Image Processing',
          '702'     : 'Fundamentals of Bioacoustics',
          '703'     : 'Biomaterials',
          '704'     : 'Biomechanics',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Medical Embedded Computing and Virtual Bio-Instrumentation Lab',
          '708P'    : 'Biomedical Signal Processing Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

BE_s8 = { '801'     : 'Communication Systems',
          '802'     : 'Biomedical Optics & Microscopy Imaging',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

BE = { 's1_s2'    : BE_s1_s2,
        's3'      : BE_s3,
        's4'      : BE_s4,
        's5'      : BE_s5,
        's6'      : BE_s6,
        's7'      : BE_s7,
        's8'      : BE_s8,
        'credits' : 206
}


CHE_s1_s2 = s1_s2

CHE_s3 = { '301'     : 'Engineering Mathematics III',
           '302'     : 'Humanities and Communication Skills',
           '303'     : 'Chemical Process Principles',
           '304'     : 'Organic Chemistry',
           '305'     : 'Chemical Engineering Thermodynamics I',
           '306'     : 'Material Science & Engineering',
           '307P'    : 'Chemistry Lab II',
           '308P'    : 'Chemical Technology Lab',
           'c301'    : 4,           'c302'    : 3,
           'c303'    : 5,           'c304'    : 4,
           'c305'    : 4,           'c306'    : 4,
           'c307P'   : 2,           'c308P'   : 2,
           'credits' : 28,
}

CHE_s4 = { '401'     : 'Engineering Mathematics IV',
           '402'     : 'Environmental Science',
           '403'     : 'Fluid and Particle Mechanics',
           '404'     : 'Physical and Analytical Chemistry',
           '405'     : 'Chemical Engineering Thermodynamics II',
           '406'     : 'Particle Technology',
           '407P'    : 'Environmental Engineering Lab',
           '408P'    : 'Materials Technology and Engineering Lab',
           'c401'    : 4,           'c402'    : 3,
           'c403'    : 5,           'c404'    : 4,
           'c405'    : 4,           'c406'    : 4,
           'c407P'   : 2,           'c408P'   : 2,
           'credits' : 28,
}

CHE_s5 = { '501'     : 'Chemical Reaction Engineering',
           '502'     : 'Petroleum Refinery Engineering & Petrochemicals',
           '503'     : 'Process Heat Transfer',
           '504'     : 'Mass Transfer Operations I',
           '505'     : 'Environmental Engineering',
           '506'     : 'Process Instrumentation',
           '507P'    : 'Fluid & Particle Mechanics Lab',
           '508P'    : 'Particle Technology Lab',
           'c501'    : 5,           'c502'    : 4,
           'c503'    : 4,           'c504'    : 4,
           'c505'    : 4,           'c506'    : 3,
           'c507P'   : 2,           'c508P'   : 2,
           'credits' : 28,
}

CHE_s6 = { '601'     : 'Chemical Process Industries',
           '602'     : 'Process Dynamics & Control',
           '603'     : 'Mass Transfer Operations II',
           '604'     : 'Economics and Management of Chemical Industries',
           '605'     : 'Energy Engineering',
           'L01'     : 'Elective I',
           '607P'    : 'Heat Transfer Operations Lab',
           '608P'    : 'Process Design Software Lab / Mini Project',
           'c601'    : 5,           'c602'    : 4,
           'c603'    : 4,           'c604'    : 4,
           'c605'    : 3,           'cL01'    : 4,
           'c607P'   : 2,           'c608P'   : 2,
           'credits' : 28,
}

CHE_s7 = { '701'     : 'Chemical Engineering Design & Drawing I',
           '702'     : 'Transport Phenomena',
           '703'     : 'Safety Engineering in Process Plants',
           '704'     : 'Biochemical Engineering',
           'L02'     : 'Elective II',
           'L03'     : 'Elective III',
           '707P'    : 'Mass Transfer Operations Lab',
           '708P'    : 'Process Control and Reaction Engineering Lab',
           '709P'    : 'Project',
           'c701'    : 5,           'c702'    : 4,
           'c703'    : 3,           'c704'    : 3,
           'cL02'    : 4,           'cL03'    : 4,
           'c707P'   : 2,           'c708P'   : 2,
           'c709P'   : 1,           'credits' : 28,
}

CHE_s8 = { '801'     : 'Chemical Engineering Design & Drawing II',
           '802'     : 'Optimization of Chemical Processes',
           'L04'     : 'Elective IV',
           'L05'     : 'Elective V',
           '805P'    : 'Seminar',
           '806P'    : 'Project',
           '807P'    : 'Viva Voce',
           'c801'    : 5,           'c802'    : 3,
           'cL04'    : 4,           'cL05'    : 4,
           'c805P'   : 2,           'c806P'   : 7,
           'c807P'   : 3,           'credits' : 28,
}

CHE = { 's1_s2'   : CHE_s1_s2,
        's3'      : CHE_s3,
        's4'      : CHE_s4,
        's5'      : CHE_s5,
        's6'      : CHE_s6,
        's7'      : CHE_s7,
        's8'      : CHE_s8,
        'credits' : 206
}


CE_s1_s2 = s1_s2

CE_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Communication Skills',
          '303'     : 'Mechanics of Solids',
          '304'     : 'Building Technology I',
          '305'     : 'Surveying I',
          '306'     : 'Engineering Geology',
          '307P'    : 'Surveying Lab I',
          '308P'    : 'Materials Testing Lab I',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

CE_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Studies',
          '403'     : 'Fluid Mechanics',
          '404'     : 'Structural Analysis I',
          '405'     : 'Engineering Economics & Principles of Management',
          '406'     : 'Surveying II',
          '407P'    : 'Surveying Lab II',
          '408P'    : 'Civil Engineering Drawing I',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

CE_s5 = { '501'     : 'Transportation Engineering I',
          '502'     : 'Structural Design I',
          '503'     : 'Open Channel Hydraulics & Hydraulic Machinery',
          '504'     : 'Geotechnical Engineering I',
          '505'     : 'Structural Analysis II',
          '506'     : 'Building Technology II',
          '507P'    : 'Civil Engineering Drawing II',
          '508P'    : 'Fluid Mechanics Lab',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

CE_s6 = { '601'     : 'Hydrology & Irrigation Engineering',
          '602'     : 'Structural Design II',
          '603'     : 'Structural Analysis III',
          '604'     : 'Geotechnical Engineering II',
          '605'     : 'Transportation Engineering II',
          'L01'     : 'Elective I',
          '607P'    : 'Geotechnical Engineering Lab',
          '608P'    : 'Materials Testing Lab II',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

CE_s7 = { '701'     : 'Structural Design III',
          '702'     : 'Design of Hydraulic Structures',
          '703'     : 'Environmental Engineering I',
          '704'     : 'Construction Engineering & Management',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Computer Applications Lab',
          '708P'    : 'Environmental Engineering Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

CE_s8 = { '801'     : 'Environmental Engineering II',
          '802'     : 'Quantity Survey & Valuation',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

CE = { 's1_s2'    : CE_s1_s2,
        's3'      : CE_s3,
        's4'      : CE_s4,
        's5'      : CE_s5,
        's6'      : CE_s6,
        's7'      : CE_s7,
        's8'      : CE_s8,
        'credits' : 206
}


CSE_s1_s2 = s1_s2

CSE_s3 = { '301'     : 'Engineering Mathematics III',
           '302'     : 'Data Structures',
           '303'     : 'Discrete Computational Structures',
           '304'     : 'Humanities and Communication Skills',
           '305'     : 'Electronic Circuits',
           '306'     : 'Switching Theory and Logic Design',
           '307P'    : 'Electronic Circuits Lab',
           '308P'    : 'Programming Lab',
           'c301'    : 4,           'c302'    : 5,
           'c303'    : 4,           'c304'    : 3,
           'c305'    : 4,           'c306'    : 4,
           'c307P'   : 2,           'c308P'   : 2,
           'credits' : 28,
}

CSE_s4 = { '401'     : 'Engineering Mathematics IV',
           '402'     : 'Environmental Studies',
           '403'     : 'Computer Organization and Design',
           '404'     : 'Programming Paradigms',
           '405'     : 'Systems Programming',
           '406'     : 'Microprocessor Based Design',
           '407P'    : 'Data Structures Lab',
           '408P'    : 'Digital Systems Lab',
           'c401'    : 4,           'c402'    : 3,
           'c403'    : 5,           'c404'    : 4,
           'c405'    : 4,           'c406'    : 4,
           'c407P'   : 2,           'c408P'   : 2,
           'credits' : 28,
}

CSE_s5 = { '501'     : 'Software Architecture and Project Management',
           '502'     : 'Industrial Economics and Principles of Management',
           '503'     : 'Signal Processing',
           '504'     : 'Operating Systems',
           '505'     : 'Digital Data Communications',
           '506'     : 'Theory Of Computation',
           '507P'    : 'Programming Paradigm Lab',
           '508P'    : 'Hardware Lab',
           'c501'    : 4,           'c502'    : 3,
           'c503'    : 4,           'c504'    : 5,
           'c505'    : 4,           'c506'    : 4,
           'c507P'   : 2,           'c508P'   : 2,
           'credits' : 28,
}

CSE_s6 = { '601'     : 'Embedded Systems',
           '602'     : 'Compiler Design',
           '603'     : 'Computer Networks',
           '604'     : 'Database Management Systems',
           '605'     : 'Computer Graphics',
           'L01'     : 'Elective I',
           '607P'    : 'Systems Lab',
           '608P'    : 'Mini Project',
           'c601'    : 4,           'c602'    : 5,
           'c603'    : 4,           'c604'    : 4,
           'c605'    : 3,           'cL01'    : 4,
           'c607P'   : 2,           'c608P'   : 2,
           'credits' : 28,
}

CSE_s7 = { '701'     : 'Wireless Networks and Mobile Communication Systems',
           '702'     : 'Design and Analysis of Algorithms',
           '703'     : 'Internet Technology',
           '704'     : 'Cryptography and Network Security',
           'L02'     : 'Elective II',
           'L03'     : 'Elective III',
           '707P'    : 'Compiler Lab',
           '708P'    : 'Network Programming Lab',
           '709P'    : 'Project',
           'c701'    : 3,           'c702'    : 5,
           'c703'    : 3,           'c704'    : 4,
           'cL02'    : 4,           'cL03'    : 4,
           'c707P'   : 2,           'c708P'   : 2,
           'c709P'   : 1,           'credits' : 28,
}

CSE_s8 = { '801'     : 'Computer Architecture and Parallel Processing',
           '802'     : 'Data Mining and Warehousing',
           'L04'     : 'Elective IV',
           'L05'     : 'Elective V',
           '805P'    : 'Project',
           '806P'    : 'Seminar',
           '807P'    : 'Viva Voce',
           'c801'    : 5,           'c802'    : 3,
           'cL04'    : 4,           'cL05'    : 4,
           'c805P'   : 7,           'c806P'   : 2,
           'c807P'   : 3,           'credits' : 28,
}

CSE = { 's1_s2'   : CSE_s1_s2,
        's3'      : CSE_s3,
        's4'      : CSE_s4,
        's5'      : CSE_s5,
        's6'      : CSE_s6,
        's7'      : CSE_s7,
        's8'      : CSE_s8,
        'credits' : 206
}


EEE_s1_s2 = s1_s2

EEE_s3 = { '301'     : 'Engineering Mathematics III',
           '302'     : 'Humanities and Communication Skills',
           '303'     : 'Electric Circuit Theory',
           '304'     : 'Electromagnetic Field Theory',
           '305'     : 'Analog Electronics',
           '306'     : 'Mechanical Engineering',
           '307P'    : 'Basic Electrical Engg Lab',
           '308P'    : 'Analog Electronics Lab',
           'c301'    : 4,           'c302'    : 3,
           'c303'    : 5,           'c304'    : 4,
           'c305'    : 4,           'c306'    : 4,
           'c307P'   : 2,           'c308P'   : 2,
           'credits' : 28,
}

EEE_s4 = { '401'     : 'Engineering Mathematics IV',
           '402'     : 'Environmental Science',
           '403'     : 'Signals and Systems',
           '404'     : 'DC Machines and Transformers',
           '405'     : 'Digital Electronics',
           '406'     : 'Electrical Measurements & Instrumentation Systems',
           '407P'    : 'Mechanical Engg. Lab',
           '408P'    : 'Electrical Measurements & Instrumentation Lab',
           'c401'    : 4,           'c402'    : 3,
           'c403'    : 5,           'c404'    : 4,
           'c405'    : 4,           'c406'    : 4,
           'c407P'   : 2,           'c408P'   : 2,
           'credits' : 28,
}

EEE_s5 = { '501'     : 'Synchronous and Induction Machines',
           '502'     : 'Power System Generation, Transmission and Distribution',
           '503'     : 'Linear Control Systems',
           '504'     : 'Power Electronics',
           '505'     : 'Digital System Design',
           '506'     : 'Electrical Material Science',
           '507P'    : 'Electrical Machines Lab I',
           '508P'    : 'Digital Electronics Lab',
           'c501'    : 5,           'c502'    : 4,
           'c503'    : 4,           'c504'    : 4,
           'c505'    : 4,           'c506'    : 3,
           'c507P'   : 2,           'c508P'   : 2,
           'credits' : 28,
}

EEE_s6 = { '601'     : 'Microprocessors and Microcontrollers',
           '602'     : 'Engineering Economics and Principles of Management',
           '603'     : 'Modern Control Theory',
           '604'     : 'Electric Drives',
           '605'     : 'Electrical Engineering Drawing',
           'L01'     : 'Elective I',
           '607P'    : 'Electrical Machines Lab II',
           '608P'    : 'Mini Project',
           'c601'    : 5,           'c602'    : 4,
           'c603'    : 4,           'c604'    : 4,
           'c605'    : 3,           'cL01'    : 4,
           'c607P'   : 2,           'c608P'   : 2,
           'credits' : 28,
}

EEE_s7 = { '701'     : 'Power System Analysis',
           '702'     : 'Analog & Digital Communication',
           '703'     : 'Digital Signal Processing',
           '704'     : 'Electrical Machine Design',
           'L02'     : 'Elective II',
           'L03'     : 'Elective III',
           '707P'    : 'Power Electronics Lab',
           '708P'    : 'Advanced Electrical Engg. Lab',
           '709P'    : 'Project',
           'c701'    : 5,           'c702'    : 4,
           'c703'    : 3,           'c704'    : 3,
           'cL02'    : 4,           'cL03'    : 4,
           'c707P'   : 2,           'c708P'   : 2,
           'c709P'   : 1,           'credits' : 28,
       }

EEE_s8 = { '801'     : 'Electrical System Design',
           '802'     : 'Power System Protection & Utilization',
           'L04'     : 'Elective IV',
           'L05'     : 'Elective V',
           '805P'    : 'Seminar',
           '806P'    : 'Project',
           '807P'    : 'Viva Voce',
           'c801'    : 5,           'c802'    : 3,
           'cL04'    : 4,           'cL05'    : 4,
           'c805P'   : 2,           'c806P'   : 7,
           'c807P'   : 3,           'credits' : 28,
}

EEE = { 's1_s2'   : EEE_s1_s2,
        's3'      : EEE_s3,
        's4'      : EEE_s4,
        's5'      : EEE_s5,
        's6'      : EEE_s6,
        's7'      : EEE_s7,
        's8'      : EEE_s8,
        'credits' : 206
}


ECE_s1_s2 = s1_s2

ECE_s3 = { '301'     : 'Engineering Mathematics III',
           '302'     : 'Humanities and Communications Skills',
           '303'     : 'Network Analysis & Synthesis',
           '304'     : 'Signals and Systems',
           '305'     : 'Digital Electronics',
           '306'     : 'Electrical Engineering',
           '307P'    : 'Digital Electronics Lab',
           '308P'    : 'Electrical Engineering Lab',
           'c301'    : 4,           'c302'    : 3,
           'c303'    : 5,           'c304'    : 4,
           'c305'    : 4,           'c306'    : 4,
           'c307P'   : 2,           'c308P'   : 2,
           'credits' : 28,
}

ECE_s4 = { '401'     : 'Engineering Mathematics IV',
           '402'     : 'Environmental Science',
           '403'     : 'Electronic Circuits',
           '404'     : 'Analog Communication',
           '405'     : 'Computer Organization & Architecture',
           '406'     : 'Solid State Devices',
           '407P'    : 'Electronic Circuits Lab',
           '408P'    : 'Analog Communication Lab',
           'c401'    : 4,           'c402'    : 3,
           'c403'    : 5,           'c404'    : 4,
           'c405'    : 4,           'c406'    : 4,
           'c407P'   : 2,           'c408P'   : 2,
           'credits' : 28,
}

ECE_s5 = { '501'     : 'Digital Signal Processing',
           '502'     : 'Quantitative Techniques for Managerial Decisions',
           '503'     : 'Electromagnetic Field Theory',
           '504'     : 'Digital Communication',
           '505'     : 'Microprocessors & Microcontrollers',
           '506'     : 'Linear Integrated Circuits',
           '507P'    : 'Microprocessors & Microcontrollers Lab',
           '508P'    : 'Linear Integrated Circuits Lab',
           'c501'    : 5,           'c502'    : 4,
           'c503'    : 4,           'c504'    : 4,
           'c505'    : 4,           'c506'    : 3,
           'c507P'   : 2,           'c508P'   : 2,
           'credits' : 28,
}

ECE_s6 = { '601'     : 'Basics of VLSI Design',
           '602'     : 'Engineering Economics and Principles of Management',
           '603'     : 'Radiation and Propagation',
           '604'     : 'Control Systems',
           '605'     : 'Optical Communication',
           'L01'     : 'Elective I',
           '607P'    : 'Digital Communication & DSP Lab',
           '608P'    : 'Mini Project',
           'c601'    : 5,           'c602'    : 4,
           'c603'    : 4,           'c604'    : 4,
           'c605'    : 3,           'cL01'    : 4,
           'c607P'   : 2,           'c608P'   : 2,
           'credits' : 28,
}

ECE_s7 = { '701'     : 'Information Theory and Coding',
           '702'     : 'Microwave Engineering',
           '703'     : 'Analog & Mixed MOS Circuits',
           '704'     : 'Digital System Design',
           'L02'     : 'Elective II',
           'L03'     : 'Elective III',
           '707P'    : 'Communication Systems Lab',
           '708P'    : 'VLSI Design Lab',
           '709P'    : 'Project',
           'c701'    : 5,           'c702'    : 4,
           'c703'    : 3,           'c704'    : 3,
           'cL02'    : 4,           'cL03'    : 4,
           'c707P'   : 2,           'c708P'   : 2,
           'c709P'   : 1,           'credits' : 28,
}

ECE_s8 = { '801'     : 'Data & Communication Network',
           '802'     : 'Wireless Mobile Communication',
           'L04'     : 'Elective IV',
           'L05'     : 'Elective V',
           '805P'    : 'Seminar',
           '806P'    : 'Project',
           '807P'    : 'Viva Voce',
           'c801'    : 5,           'c802'    : 3,
           'cL04'    : 4,           'cL05'    : 4,
           'c805P'   : 2,           'c806P'   : 7,
           'c807P'   : 3,           'credits' : 28,
}

ECE = { 's1_s2'   : ECE_s1_s2,
        's3'      : ECE_s3,
        's4'      : ECE_s4,
        's5'      : ECE_s5,
        's6'      : ECE_s6,
        's7'      : ECE_s7,
        's8'      : ECE_s8,
        'credits' : 206
}


IT_s1_s2 = s1_s2

IT_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Communication Skills',
          '303'     : 'Data Structures',
          '304'     : 'Discrete Computational Structures',
          '305'     : 'Electronic Circuits',
          '306'     : 'Switching Theory & Logic Design',
          '307P'    : 'Digital Electronics Lab',
          '308P'    : 'Programming Lab',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

IT_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Studies',
          '403'     : 'Computer Organization & Design',
          '404'     : 'Principles of Communication Engineering',
          '405'     : 'Data Modeling And Design',
          '406'     : 'Microprocessor Based Design',
          '407P'    : 'Data Structures Lab',
          '408P'    : 'Programming Environments Lab',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

IT_s5 = { '501'     : 'Software Architecture & Project Management',
          '502'     : 'Industrial Economics and Principles of Management',
          '503'     : 'Embedded Systems',
          '504'     : 'Operating Systems',
          '505'     : 'Digital Data Communication',
          '506'     : 'Theory of Computation',
          '507P'    : 'Systems Lab',
          '508P'    : 'Hardware Lab',
          'c501'    : 5,           'c502'    : 3,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 4,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

IT_s6 = { '601'     : 'Software Quality Management',
          '602'     : 'Compiler Design',
          '603'     : 'Computer Networks',
          '604'     : 'Database Management Systems',
          '605'     : 'Human Computer Interaction',
          'L01'     : 'Elective I',
          '607P'    : 'Database Management Lab',
          '608P'    : 'Mini Project',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

IT_s7 = { '701'     : 'Computer Graphics',
          '702'     : 'Natural Language Processing And Knowledge Based Systems',
          '703'     : 'Internet Technology',
          '704'     : 'Cryptography and Network Security',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Network Programming Lab',
          '708P'    : 'Computer Graphics and Multimedia Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 3,
          'c703'    : 3,           'c704'    : 4,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

IT_s8 = { '801'     : 'Mobile Communication System',
          '802'     : 'High Speed Networks',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

IT = { 's1_s2'    : IT_s1_s2,
        's3'      : IT_s3,
        's4'      : IT_s4,
        's5'      : IT_s5,
        's6'      : IT_s6,
        's7'      : IT_s7,
        's8'      : IT_s8,
        'credits' : 206
}


IC_s1_s2 = s1_s2

IC_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Communication Skills',
          '303'     : 'Basic Instrumentation Engineering and Transducers',
          '304'     : 'Digital Electronics',
          '305'     : 'Analog Devices and Circuits',
          '306'     : 'Electrical Measurements and Measuring Instruments',
          '307P'    : 'Digital Electronics Lab',
          '308P'    : 'Analog Devices and Circuits Lab',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

IC_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Studies',
          '403'     : 'Control Engineering I',
          '404'     : 'Electrical Machines and Drives',
          '405'     : 'Mechanical Instrumentation',
          '406'     : 'Electric Circuits and Network Theory',
          '407P'    : 'Electrical Measurements and Machines Lab',
          '408P'    : 'Transducers Lab',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

IC_s5 = { '501'     : 'Control Engineering II',
          '502'     : 'Communication and Telemetry',
          '503'     : 'Microcontrollers',
          '504'     : 'Industrial Instrumentation I',
          '505'     : 'Linear Integrated Circuits',
          '506'     : 'Analytical Instruments',
          '507P'    : 'Mechanical Instrumentation Lab',
          '508P'    : 'Linear Integrated Circuits Lab',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

IC_s6 = { '601'     : 'Signal Processing',
          '602'     : 'Engineering Economics and Principles of Management ',
          '603'     : 'Microprocessors',
          '604'     : 'Industrial Instrumentation II',
          '605'     : 'Process Control Instrumentation',
          'L01'     : 'Elective I',
          '607P'    : 'Industrial Instrumentation Lab',
          '608P'    : 'Microprocessors and Microcontrollers Lab',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

IC_s7 = { '701'     : 'Industrial Process Control',
          '702'     : 'Biomedical Instrumentation',
          '703'     : 'Computer Control of Processes',
          '704'     : 'Optoelectronic Instrumentation ',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Process Control and Virtual Instrumentation Lab',
          '708P'    : 'Control Systems and Simulation Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

IC_s8 = { '801'     : 'Instrumentation System Design',
          '802'     : 'Power Plant Instrumentation',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

IC = { 's1_s2'    : IC_s1_s2,
        's3'      : IC_s3,
        's4'      : IC_s4,
        's5'      : IC_s5,
        's6'      : IC_s6,
        's7'      : IC_s7,
        's8'      : IC_s8,
        'credits' : 206
}


ME_s1_s2 = s1_s2

ME_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Communication Skills',
          '303'     : 'Fluid Mechanics',
          '304'     : 'Computer Assisted Machine Drawing',
          '305'     : 'Electrical Technology',
          '306'     : 'Metallurgy & Material Science',
          '307P'    : 'Electrical Engineering Lab',
          '308P'    : 'Production Engineering Lab I',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

ME_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Studies',
          '403'     : 'Mechanics of Solids',
          '404'     : 'Casting and Joining',
          '405'     : 'Fluid Machinery',
          '406'     : 'Thermodynamics',
          '407P'    : 'Material Testing Lab',
          '408P'    : 'Production Engineering Lab II',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

ME_s5 = { '501'     : 'Heat and Mass Transfer',
          '502'     : 'Advanced Mechanics of Solids',
          '503'     : 'Engineering Economics and Principles of Management',
          '504'     : 'IC Engines and Gas Turbines',
          '505'     : 'Mechanics of Machinery',
          '506'     : 'Metal Cutting and Forming',
          '507P'    : 'Fluids Lab',
          '508P'    : 'Thermal Lab I',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

ME_s6 = { '601'     : 'Dynamics of Machinery',
          '602'     : 'Finite Element Method ',
          '603'     : 'Machine Design I',
          '604'     : 'Operation Research',
          '605'     : 'Computer Integrated Manufacturing',
          'L01'     : 'Elective I',
          '607P'    : 'Mini Project / Lab',
          '608P'    : 'Thermal Lab II',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

ME_s7 = { '701'     : 'Machine Design II',
          '702'     : 'Operations Management',
          '703'     : 'Metrology and Instrumentation',
          '704'     : 'Power Plant Engineering',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'CAD Lab',
          '708P'    : 'Instrumentation Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

ME_s8 = { '801'     : 'Refrigeration and Air Conditioning',
          '802'     : 'Compressible Fluid Flow',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

ME = { 's1_s2'    : ME_s1_s2,
        's3'      : ME_s3,
        's4'      : ME_s4,
        's5'      : ME_s5,
        's6'      : ME_s6,
        's7'      : ME_s7,
        's8'      : ME_s8,
        'credits' : 206
}


PT_s1_s2 = s1_s2

PT_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Communication Skills',
          '303'     : 'Graphic reproduction and Colour separation',
          '304'     : 'Mechanics of Solids',
          '305'     : 'Electrical Machines and Measurements',
          '306'     : 'Thermal Engineering',
          '307P'    : 'Machine Drawing',
          '308P'    : 'Basic Electrical and Electronics Engg. Lab',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

PT_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Studies',
          '403'     : 'Offset Machinery I',
          '404'     : 'Theory of Mechanism',
          '405'     : 'Electronic Circuits',
          '406'     : 'Paper & Ink',
          '407P'    : 'Printing Machines Lab I',
          '408P'    : 'Quality Control Lab',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

PT_s5 = { '501'     : 'Offset Machinery II',
          '502'     : 'Digital Printing',
          '503'     : 'Engineering Economics and Principles of Management',
          '504'     : 'Design & Planning for Media Production',
          '505'     : 'Microprocessor & Microcontrollers',
          '506'     : 'Printing Measurements & Control Instruments',
          '507P'    : 'Printing Machine Lab II',
          '508P'    : 'DTP Lab',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

PT_s6 = { '601'     : 'Flexogaphy',
          '602'     : 'Instrumentation & Control',
          '603'     : 'Design of Machine Elements',
          '604'     : 'Print Finishing & Converting',
          '605'     : 'Screen Printing & Gravure',
          'L01'     : 'Elective I',
          '607P'    : 'Print Finishing Lab ',
          '608P'    : 'Screen Printing & Flexo Lab',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

PT_s7 = { '701'     : 'Packaging Technology',
          '702'     : 'Electrical Drives and Control',
          '703'     : 'Tone and Color Analysis',
          '704'     : 'Printing Machinery and Maintenance',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Tone and Color Analysis Lab',
          '708P'    : 'Packaging Technology Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

PT_s8 = { '801'     : 'Print Management Costing & Estimating',
          '802'     : 'Quality Control in Printing',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

PT = { 's1_s2'    : PT_s1_s2,
        's3'      : PT_s3,
        's4'      : PT_s4,
        's5'      : PT_s5,
        's6'      : PT_s6,
        's7'      : PT_s7,
        's8'      : PT_s8,
        'credits' : 206
}


PE_s1_s2 = s1_s2

PE_s3 = { '301'     : 'Engineering Mathematics III',
          '302'     : 'Humanities and Social Science',
          '303'     : 'Electrical Drives and Automation',
          '304'     : 'Mechanics of Solids',
          '305'     : 'Metallurgy and Material Science',
          '306'     : 'Machine Tool Technology',
          '307P'    : 'Production Engineering Drawing',
          '308P'    : 'Machine Tool Lab I',
          'c301'    : 4,           'c302'    : 3,
          'c303'    : 5,           'c304'    : 4,
          'c305'    : 4,           'c306'    : 4,
          'c307P'   : 2,           'c308P'   : 2,
          'credits' : 28,
}

PE_s4 = { '401'     : 'Engineering Mathematics IV',
          '402'     : 'Environmental Science',
          '403'     : 'Theory of Machines',
          '404'     : 'Fluid Mechanics and Machinery',
          '405'     : 'Design of Machine Elements',
          '406'     : 'Thermal Engineering',
          '407P'    : 'Electrical and Electronics Lab',
          '408P'    : 'Mechanical Engineering Lab',
          'c401'    : 4,           'c402'    : 3,
          'c403'    : 5,           'c404'    : 4,
          'c405'    : 4,           'c406'    : 4,
          'c407P'   : 2,           'c408P'   : 2,
          'credits' : 28,
}

PE_s5 = { '501'     : 'Industrial Automation',
          '502'     : 'Computational Methods in Engineering',
          '503'     : 'Welding and Allied Processes',
          '504'     : 'Metal Casting',
          '505'     : 'Machining of Materials',
          '506'     : 'Engineering Economics and Principles of Management',
          '507P'    : 'Machine Tool Lab II',
          '508P'    : 'Material Testing Lab',
          'c501'    : 5,           'c502'    : 4,
          'c503'    : 4,           'c504'    : 4,
          'c505'    : 4,           'c506'    : 3,
          'c507P'   : 2,           'c508P'   : 2,
          'credits' : 28,
}

PE_s6 = { '601'     : 'Tool Engineering',
          '602'     : 'Metal Forming',
          '603'     : 'Industrial Engineering',
          '604'     : 'Instrumentation and Control',
          '605'     : 'Inspection and Quality Control',
          'L01'     : 'Elective I',
          '607P'    : 'Manufacturing Sciences Lab',
          '608P'    : 'CAD/CAM Lab',
          'c601'    : 5,           'c602'    : 4,
          'c603'    : 4,           'c604'    : 4,
          'c605'    : 3,           'cL01'    : 4,
          'c607P'   : 2,           'c608P'   : 2,
          'credits' : 28,
}

PE_s7 = { '701'     : 'Production Management',
          '702'     : 'Operations Research I',
          '703'     : 'Maintenance Engineering & Management',
          '704'     : 'Management Information Systems',
          'L02'     : 'Elective II',
          'L03'     : 'Elective III',
          '707P'    : 'Industrial Engineering Lab',
          '708P'    : 'Metrology Lab',
          '709P'    : 'Project',
          'c701'    : 5,           'c702'    : 4,
          'c703'    : 3,           'c704'    : 3,
          'cL02'    : 4,           'cL03'    : 4,
          'c707P'   : 2,           'c708P'   : 2,
          'c709P'   : 1,           'credits' : 28,
}

PE_s8 = { '801'     : 'Financial Management',
          '802'     : 'Computer Integrated Manufacturing',
          'L04'     : 'Elective IV',
          'L05'     : 'Elective V',
          '805P'    : 'Seminar',
          '806P'    : 'Project',
          '807P'    : 'Viva Voce',
          'c801'    : 5,           'c802'    : 3,
          'cL04'    : 4,           'cL05'    : 4,
          'c805P'   : 2,           'c806P'   : 7,
          'c807P'   : 3,           'credits' : 28,
}

PE = { 's1_s2'    : PE_s1_s2,
        's3'      : PE_s3,
        's4'      : PE_s4,
        's5'      : PE_s5,
        's6'      : PE_s6,
        's7'      : PE_s7,
        's8'      : PE_s8,
        'credits' : 206
}


STREAM = { 'Aeronautical Engineering'                          : AE,
           'Applied Electronics & Instrumentation Engineering' : AEIE,
           'Automobile Engineering'                            : AME,
           'Biotechnology'                                     : BT,
           'Biomedical Engineering'                            : BE,
           'Chemical Engineering'                              : CHE,
           'Civil Engineering'                                 : CE,
           'Computer Science and Engineering'                  : CSE,
           'Electrical & Electronics Engineering'              : EEE,
           'Electronics and Communication Engineering'         : ECE,
           'Information Technology'                            : IT,
           'Instrumentation & Control Engineering'             : IC,
           'Mechanical Engineering'                            : ME,
           'Printing Technology'                               : PT,
           'Production Engineering'                            : PE,
}


STREAM_CODE = OrderedDict()
STREAM_CODE['']  = ''
STREAM_CODE['AE']   = 'Aeronautical Engineering'
STREAM_CODE['AEIE'] = 'Applied Electronics & Instrumentation Engineering'
STREAM_CODE['AME']  = 'Automobile Engineering'
STREAM_CODE['BT']   = 'Biotechnology'
STREAM_CODE['BE']   = 'Biomedical Engineering'
STREAM_CODE['CHE']  = 'Chemical Engineering'
STREAM_CODE['CE']   = 'Civil Engineering'
STREAM_CODE['CSE']  = 'Computer Science and Engineering'
STREAM_CODE['EEE']  = 'Electrical & Electronics Engineering'
STREAM_CODE['ECE']  = 'Electronics and Communication Engineering'
STREAM_CODE['IT']   = 'Information Technology'
STREAM_CODE['IC']  = 'Instrumentation & Control Engineering'
STREAM_CODE['ME']   = 'Mechanical Engineering'
STREAM_CODE['PT']   = 'Printing Technology'
STREAM_CODE['PE']   = 'Production Engineering'
